### ISSUE TITLE
Maximized window with gaps

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#10]
How about to add option to maximize current window but keep monitor gaps (padding) and (optionally) borders around it.

**Comment by tudurom** [comment]
How should I name the waitron command? `window_enlarge`?

**Comment by dialuplama** [comment]
Maybe `window_monocle`?

**Comment by tudurom** [comment]
Yeah, that sounds great, thanks!

**Comment by tudurom** [comment]
35892064b312d596e0a25d4625fc71fbf06c2550
