### ISSUE TITLE
Add option(s) to set separate gap_width (monitor padding) for different sides

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#11]
It would be useful for statusbars/panels

**Comment by tudurom** [comment]
Statusbars and panels are completely ignored by windowchef. If you have more use cases, let me know.

**Comment by dialuplama** [comment]
Well, for example i set top statusbar with 30px height and monitor paddding 18px. Now when i'm using window_snap or grid or horizontal/vertical maximize the window will overlap statusbar. To avoid this i need to set bigger top padding separately.
![2016-10-07-185600_1920x1200_scrot](https://cloud.githubusercontent.com/assets/16153634/19196832/c3f8e394-8cbf-11e6-88a2-aee26460538a.png)

**Comment by tudurom** [comment]
Oooooh, I get it! Working on it!

**Comment by tudurom** [comment]
Done in 0e515099f7d1a53a5840a15dd7aa4006c129ca05
