### ISSUE TITLE
Add more positions to window_snap

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#12]
How about to add top, left, right, bottom positions in window_snap.

**Comment by tudurom** [comment]
Will do!

**Comment by tudurom** [comment]
How should left behave? Align window to centered on the left?

**Comment by dialuplama** [comment]
Maximize window in vertical (or horizontal for top/bottom) and align it to needed side.

**Comment by tudurom** [comment]
you can do it by `{h,v}maximizing` the window and snapping it to the center tho

**Comment by dialuplama** [comment]
Oh, you are right.

> Align window to centered on the left?

So maybe implement this behave then. Don't know if it really needed.
