### ISSUE TITLE
waitron subscribe option

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#13]
How about to add option in waitron that will print status information (e.g. group changes). Just like in herbstluftwm/bspwm.

**Comment by tudurom** [comment]
No need for that, you can get group info by `xprop`ing the root window. Information about windows and events can be get by `wattr` and `wew` from wmutils. I may add special root window properties with informations about the state of the wm. In fact, communication between waitron and windowchef is one way, the wm cannot send information to waitron.

**Comment by dialuplama** [comment]
Using `xprop` seems is good solution for me. Will try to test it later.

**Comment by tudurom** [comment]
Closing this.
