### ISSUE TITLE
Send windows to monitor

### ISSUE THREAD

**Issue by n1kolas** [tudurom/windowchef#15]
I think it would be nice if you had the possibility to move windows to another monitor.
At best this causes the window to stay in the same place (if it's centered, keep it centered, independent of resolution change - not sure if this is always possible though, probably have to keep it percentage based).

`
./waitron window_send_mon VGA-1
`

Maybe this could also be done in a more generic way (which I would prefer).
As in sending the window to the left or right monitor relative to the current one (if furthest left and you send to left, do nothing or send it to furthest right).
I could see how this causes problems if one sets up the monitorscreen above the other one.
Not sure if you would want to implement "up".

`
./waitron window_send_mon left|right
`

Another possibility would be to number them from left to right, so you could send from monitor three to monitor one (could also be done by sending to right and choosing the furthest left again as mentioned above). Again there's a problem with order if you set one screen on top of the other one.

`
./waitron window_send_mon 1
`

I think option one might be too much configuration, also it's annoying if you have to use a different monitor setup. I'd prefer option two.

I'm not sure how useful this is for the most, I know for example wmutils is pretty strict on multihead support as it is kind of against the whole minimalism idea (although I read it's mainly because no devs use it). But since it has some support here, I figured I'd ask if this could be in scope.

**Comment by tudurom** [comment]
You can use [disputils](https://arcetera.moe/git/disputils/log.html) (I and arc made it :3). It will be sooner or later integrated in wmutils.

**Comment by n1kolas** [comment]
Yea, I used it before in conjuction with wmutils and it worked great.
I just thought this could be done natively without the necessary shell scripting.
I wasn't sure if this is something you would see in windowchef.

Something else I was missing was the "closest" directional focus. But then again one could just use the wmutils implementation (I know it's "just" a shell script too).

Not sure how much out of the box features you want for the tool since basically you could do everything with some scripting + wmutils (well not multihead, but disputils works great for that).

I mean disputils will work, just not sure where you kind of set the end of the scope for this.
Maybe this is something to elaborate a bit more in the readme as there are some window managers who deal with this without third party.

Glad to hear disputils gets into wmutils tho! Great tool.

**Comment by tudurom** [comment]
Yeah, totally forgot about writing a [rationale for this wm in the readme](https://github.com/tudurom/windowchef#rationale). Thanks for reminding me that!

As for this feature you're requesting, I will not implement it. Instead, I will write a set of useful scripts for disputils (like wmutils did with contrib).
