### ISSUE TITLE
show only a specific group

### ISSUE THREAD

**Issue by dzklaim** [tudurom/windowchef#18]
I would like to suggest the option to show only a specific group.  I couldn't find a reference for this option in the man page.  Windowchef seems great! thanks

**Comment by tudurom** [comment]
Implementing it right now. This and sticky groups can be used to emulate workspaces, which is good. Thanks for the suggestion!

**Comment by tudurom** [comment]
Done in b8d6c4c482def0c62ebd44c2f92ebf5f691af2c4
