### ISSUE TITLE
xprop always show 0 for current group/workspace

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#22]
`xprop -root _NET_CURRENT_DESKTOP` always show `_NET_CURRENT_DESKTOP(CARDINAL) = 0`. No difference which group is activated.

**Comment by tudurom** [comment]
of course it shows 0. multiple groups can be activated at the same time. there is no EWMH property for groups.

**Comment by dialuplama** [comment]
So is there way to know current active group/workspace?

**Comment by tudurom** [comment]
no. i think i am going to implement windowchef-specific root window properties to handle such situations.

**Comment by dialuplama** [comment]
would be nice

**Comment by tudurom** [comment]
Happy New Year! 3f4aada5384d7eca8a08681e1265d7bf91539e8b
