### ISSUE TITLE
click to focus

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#23]
Maybe it possible to add "click to focus" feature. I suppose that for some people it would be more natural than "sloppy focus".
I tried to achieve this behavior with `underneath.sh` from wmutils contrib repo, but it doesn't work with drop-down menus. Also there is [xqp](https://github.com/baskerville/xqp) tool from baskerville. Unfortunately it also has issue with drop-down menus in some apps.

**Comment by tudurom** [comment]
I don't know if I can fix the dropdown issue. Dropdowns are windows on their own and are ignored by windowchef completely.

**Comment by dialuplama** [comment]
Well, found that when using `waitron window_focus $(xqp)` the issue with dropdown appear only in electron based applications (chromium, atom, etc.) Maybe it will be helpful.

**Comment by tudurom** [comment]
I think that you can solve it by replacing `waitron window_focus $(xqp)` with `test "$(pfw)" != "$(xqp)" && waitron window_focus $(xqp)`.

**Comment by dialuplama** [comment]
It's works! Thank you.
