### ISSUE TITLE
Lemonbar was renamed to Polybar

### ISSUE THREAD

**Issue by warmwaffles** [tudurom/windowchef#24]
https://github.com/jaagr/polybar

Just saw this on the readme

**Comment by tudurom** [comment]
[Wrong](https://github.com/jaagr/polybar/commit/fd57ab0f3deb2d6e9076bb02a7e84a0601e7f3a7). Polybar back in the day was named "lemonbuddy". It generated output for [lemonbar](https://github.com/LemonBoy/bar), which is a simple program that draws a bar with text and some formatting. Lemonbuddy generated the content for the bar, which was piped into lemonbar to be drawn on the screen. Polybar draws the bar on its own now.

So Polybar / Lemonbuddy and lemonbar are different projects.

Closing.
