### ISSUE TITLE
waitron window_put_in_grid wrong sizes

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#25]
The issue with 2x1 and 1x2 virtual grid.

With `waitron window_put_in_grid 2 1 0 0` and `waitron window_put_in_grid 2 1 1 0` the bottom gaps larger than should be.

With `waitron window_put_in_grid 1 2 0 1` part of the window goes out of screen.

**Comment by tudurom** [comment]
try again with the latest fix

**Comment by dialuplama** [comment]
works great, thank you
