### ISSUE TITLE
wmctrl issues

### ISSUE THREAD

**Issue by zenlinux** [tudurom/windowchef#30]
Greetings.

I have the following in my sxhkdrc:

super + ctrl + e
    wmctrl -a emacs

super + ctrl + w
    wmctrl -a st

super + ctrl + q
    wmctrl -a vimperator

The problem is that it raises the window but keeps the focus ( keyboard input ) in the current window. Also to note : Right after I start the window manager using startx it works but after two or three super + ctrl + w etc it stops working.

Can you please check this?
    
Edit: Sometimes it keeps on working for a while and randomly stops working.

Edit for more info: I use tint2 with windowchef and after I close the last window the name still shows up in tint2. 
For e.g. startx -> start urxvt ( by pressing Super + Return ) -> start xterm ( from urxvt command line ).    
    Alt + Tab between windows and tint2 updates correctly. 
Close urxvt by typing exit. tint2 now shows only xterm ( which is the expected behaviour)
Close xterm by typing exit. tint2 still shows xterm ( which is =not= the expected behaviour).
I believe this is connected to the issue I described earlier.

**Comment by tudurom** [comment]
I don't know what kind of magic wmctrl uses to give focus to windows by workspace. Also, does the tint2 issue happen only when you use wmctrl? If no, then consider opening a new issue.

**Comment by zenlinux** [comment]
@tudurom Sorry for the late report. I have checked again and irrespective of whether I use wmctrl or xdo, I get the same erroneous behaviour.
