### ISSUE TITLE
Switching groups using `group_activate_specific` doesn't save the stacking order.

### ISSUE THREAD

**Issue by CamilleScholtz** [tudurom/windowchef#33]
Example,

* Before I switch forth and back between group 1 and 2: https://punpun.xyz/o2hv.png
* After: https://punpun.xyz/vzp8.png

This is probably also the case for any of the other `group_` commands.

**Comment by tudurom** [comment]
It is intended behavior. And also hard to avoid behavior.

Right now I am not at home, I will return tomorrow. I will check all the issues and the PR then.

Thanks for reporting!

**Comment by CamilleScholtz** [comment]
I'm not exactly sure how windows get mapped, but it might be possible to map them (when switching/toggling a group) in an order that would make them appear in the same stacking order.

**Comment by tudurom** [comment]
We can save the stacking order of the windows relative to the group (I think), like window 1A is on top of window 1B that is under 1C but we cannot save stacking order details like 1A is under 2A (the first digit is the group number in my example).

**Comment by CamilleScholtz** [comment]
I use windowchef with the sticky option enabled, so that wouldn't be a problem for me I think ;).

**Comment by tudurom** [comment]
Well I don't want to implement a feature that only works with sticky groups, perhaps you can write a script and add it to the contrib directory?

**Comment by CamilleScholtz** [comment]
It seems like lsw prints windows in the stacked order (or maybe last focused order?), anyways I think this might be scriptable yes, closing this then.
