### ISSUE TITLE
toggling out of fullscreen mode with mpv doesn't 90% of the time.

### ISSUE THREAD

**Issue by CamilleScholtz** [tudurom/windowchef#34]
when pressing `f` or double clicking `mpv` it toggles into fullscreen mode just fine, however I have to try toggling it a dozen of times before it finally toggles back to normal mode for some reason.

**Comment by tudurom** [comment]
It runs as expected for me, I don't know which might be the cause. Perhaps you can try older git commits and see which one is the culprit?

**Comment by tudurom** [comment]
I made a possible fix, even released it. Try it now to see if it works.
