### ISSUE TITLE
Crashes from time to time

### ISSUE THREAD

**Issue by greduan** [tudurom/windowchef#36]
Sadly I can't tell you with details, because it crashes randomly (or semi randomly). It seems that sometimes, when I close a termite window it decides to crash. It has happened twice now, both times with a termite window, I don't have a pattern for what caused it though.

**Comment by tudurom** [comment]
Compile windowchef in debug mode

```
$ make clean && make debug && sudo make install
```

Then in your `.xinitrc` launch windowchef like this

```bash
exec windowchef 2>wchf.log
```

To save all debug logs in a file. Then post the file here.

**Comment by tudurom** [comment]
Hopefully someone will find us :)

**Comment by greduan** [comment]
Haha I'm lazy. If it crashes again I'll do it, since it isn't just a fluke then.
