### ISSUE TITLE
[REQ] Please add default workspace

### ISSUE THREAD

**Issue by S0rryMyBad** [tudurom/windowchef#37]
Dear tudor,
i really love this wm so much! but, it's not friendly when i using it. i mean, it's not include default workspace so we have to adding manually. Can u just adding the default workspaces like dwm , 2bwm?

Thanks before, keep it up! :)

**Comment by tudurom** [comment]
Windowchef doesn't have workspaces like dwm and 2bwm, it has "groups". Multiple groups can be activated at the same time to show all of the groups' windows on the screen. If you only have one group activated, you're essentially emulating workspace functionality.

Now, I don't understand what you mean by "default workspace". I will try to assume what you mean and help you based on the assumption.

If...

* you want the window to automatically be added to the last active group, then you can just enable the "sticky windows" mode (`waitron wm_config sticky_windows true`). Together with the `group_activate_specific` command you can achieve full workspace emulation.

* you want newly created windows to get automatically assigned to some group by some rule (for example, you want all browser windows on workspace two), then windowchef doesn't have that functionality built-in. I wrote a tool named [ruler](https://github.com/tudurom/ruler) that does exactly that though.

**Comment by S0rryMyBad** [comment]
i mean, default workspaces "tags" like in dwm.. by default, dwm has 9 tags "1,2,3,4,5,6,7,8,9" can u make it for windowchef?

**Comment by tudurom** [comment]
Can't you just add `waitron wm_config groups_nr 9` in your `.windowchefrc`?

**Comment by myugan** [comment]
maybe, you can close this issue @tudurom.
