### ISSUE TITLE
[REQ] Enable internal/external border

### ISSUE THREAD

**Issue by myugan** [tudurom/windowchef#40]
Maybe you can add this, i mean this wm can be cool with internal/external border on focus/unfocus window too. The user can modify this config this config on their windowchefrc for example
```
watron wm_config internal_border value
waitron wm_config external_border value
```

Keep it up 😄

**Comment by tudurom** [comment]
I once had this crazy idea of letting the user specify the number of borders and define each one of them. I will reconsider it!

**Comment by myugan** [comment]
Done! thx yuune https://github.com/yuune/windowchef/commit/748611e6f544d6ba65c1bfdc68494b8bc541115b

**Comment by tudurom** [comment]
It is now in `master`.
