### ISSUE TITLE
Windowchef doesn't support _NET_DESKTOP_VIEWPORT on Polybar

### ISSUE THREAD

**Issue by myugan** [tudurom/windowchef#41]
I try to using polybar as panel on windowchef and running it but an error appear like this :
![ewmh](https://user-images.githubusercontent.com/20453528/35469857-e39e06d8-0370-11e8-8f15-1596efe30576.png)

I mean the workspace status like this : 
![workspace](https://user-images.githubusercontent.com/20453528/35469862-fc56cbd8-0370-11e8-8e56-1f36091de629.png)

Polybar (https://github.com/jaagr/polybar) use module script, unlike other panel : dzen2, lemonbar. You can add number/word for workspace status. Thx

**Comment by tudurom** [comment]
Should be fixed, try it and confirm that it's working.

Nice desktop btw

**Comment by kjaklinovic** [comment]
Does this mean that windowchef should be able to work with polybars module "internal/xworkspaces" ?
