### ISSUE TITLE
waitron window_snap middle doesn't respect gap_width.

### ISSUE THREAD

**Issue by Vurgak** [tudurom/windowchef#45]
When using `waitron window_snap middle` window is set exactly in the middle of the screen, ignoring gaps.
![2018-02-07-100311_1366x768_scrot](https://user-images.githubusercontent.com/33526468/35907411-2478b1be-0bee-11e8-95ba-1d03ae132775.png)

**Comment by ghost** [comment]
i think the window_snap middle is already do the right things, even the others snap position is ignoring others gaps except the position itself. 
e.g. `waitron window_snap topright`
![chiisu-2018-02-20-08-48-09](https://user-images.githubusercontent.com/9277632/36404059-3cdfb39c-161b-11e8-8795-d89867a461d3.png)
