### ISSUE TITLE
windowchef does not respect wmutil's chwb

### ISSUE THREAD

**Issue by JLErvin** [tudurom/windowchef#51]
`windowchef` is advertised as 

> 100% compatible with window management utilities (e.g. wmutils). Windowchef will update its internal state if programs attempt to manage windows. It also applies the correct window decorations when a program focuses a window. This makes it possible to use it as a "backend" with wm utilities

Howver, running `chwb` does not change `windowchef`'s border settings. 

For example, runnig
```
chwb -s 0 $(pfw)
```

Will move the window as if the border has been changed (this is documented in `chwb`), but the window border remains unchanged using both single and double borders. 

Running `wattr b $(pfw)` shows that border size is unaffected.

**Comment by Jemi** [comment]
I'm getting the same thing here running the latest git of windowchef.  After setting border width to 0 using waitron wm_config border_width 0 and disabling borders using waitron enable_borders false - which according to the man page is supposed to enable the use of an external utility to set borders - the following commands have no effect:

chwb -s FFFFFF -c 1 0x1600006

-and-

chwb -s FFFFFF -c 1 $(pfw)

These commands also print no error message.  So this bug appears to be confirmed.

**Comment by tudurom** [comment]
Fixed. To modify borders with external tools you must disable borders first:

```bash
waitron wm_config enable_borders false
```
