### ISSUE TITLE
 window_put_in_grid - Suggestion

### ISSUE THREAD

**Issue by kjaklinovic** [tudurom/windowchef#52]
It would be awesome if there was also an option to define how many cells to occupy.
Example:  `waitron window_put_in_grid  5  5  1 1  2  3` 
Last two numbers "2  3"would define how many cells to occupy in width (2) and height (3).

**Comment by tudurom** [comment]
![screenshot](https://i.imgur.com/5KPC7xI.png)

Like this? :P

**Comment by kjaklinovic** [comment]
Exactly like this ! Thank you :)
