### ISSUE TITLE
windowchef doesn't react to waitron

### ISSUE THREAD

**Issue by asyncial** [tudurom/windowchef#58]
Hey,
I really like the idea of this window manager, but I don't quite get it to work. I run windowchef with`exec windowchef` in my `.xinitrc`, but it doesn't react to anything specified in the (example) windowchefrc file. I can open urxvt via sxhkd, but I can't do anything else. I tried moving a terminal window around with the `waitron` command, but nothing happens, not even a error message. I'm using the binary package of voidlinux.
Thanks in advance for your help.

**Comment by tudurom** [comment]
mismatched windowchef and waitron versions / builds most probably. you can try previous git commits and spot the odd one

**Comment by asyncial** [comment]
Thanks for the fast answer, I accidentally clicked to fast on create, before actually writing anything... But about your comment: I use version 0.4.2 from the voidlinux repositories. Is your advice still relevant? Because a version mismatch should not be possible in this case, is it?

**Comment by asyncial** [comment]
The behaviour is actually pretty similar to this issue: [No borders, no waitron commands work on Cinnamon ](https://github.com/tudurom/windowchef/issues/35)

**Comment by asyncial** [comment]
I also get an error message on startx: "windowchef: couldn't load config file". The config file is located in `~/.config/windowchef/windowchefrc`

**Comment by tudurom** [comment]
Try again now, I added better error messages.
