### ISSUE TITLE
Feature: move and resize windows with the mouse (half-done)

### ISSUE THREAD

**Issue by tudurom** [tudurom/windowchef#6]
Any interest?

**Comment by dialuplama** [comment]
+1 Would be nice feature

**Comment by tudurom** [comment]
It is half-done. See the manpage for `waitron(1)`.

**Comment by bkruczyk** [comment]
I don't know if this should be separate feature request but would it be possible to add window movement by clicking-and-draging window top border like in evilwm? And thus providing click-to-focus-and-raise behaviour?

**Comment by dialuplama** [comment]
1. Is it possible to add options to move/resize with different mouse buttons (e.g. move with left button, resize with right)

2. Also i have notice that when you do move and mouse pointer isn't on window center, the window is "jumping", the similar behavior with when you do resize. It is not big deal, but it would be nice if moving/resizing windows would be more "smooth"

**Comment by dialuplama** [comment]
Found related bug. 

After shrink window with mouse you can't move it (with mouse) to the end of right or bottom edge of screen. 
After expand window with mouse you can move it (with mouse) out of screen edges (normally you can't)

Also there is no problem if using `waitron window_move`

**Comment by tudurom** [comment]
> 1. Is it possible to add options to move/resize with different mouse buttons (e.g. move with left button, resize with right)

I think I am going to either remove `mouse_*` commands altogether or to rewrite them and make mouse commands behave like in other window managers like cwm or bspwm where you hold the super key and a mouse button and start moving the window, instead of toggling a "resize mode".

> 2. Also i have notice that when you do move and mouse pointer isn't on window center, the window is "jumping", the similar behavior with when you do resize. It is not big deal, but it would be nice if moving/resizing windows would be more "smooth"

I really don't know what to do with it. Sorry :(

> Found related bug.
> 
> After shrink window with mouse you can't move it (with mouse) to the end of right or bottom edge of screen.
> After expand window with mouse you can move it (with mouse) out of screen edges (normally you can't)
> 
> Also there is no problem if using waitron window_move

Fixed. I'm going to push it.

**Comment by tudurom** [comment]
Ok. My [PR to wmutils](https://github.com/wmutils/opt/pull/26) was merged. I will remove all `mouse_*` commands in favor of `xmmv(1)` and `xmrs(1)`.
