### ISSUE TITLE
windowchef: "couldn't load config file"

### ISSUE THREAD

**Issue by Flouzr** [tudurom/windowchef#60]
I am having a problem loading windowchef. In .xinitrc I have tried both `exec windowchef` and `exec windowchef -c` neither of which work. Also I do have `XDG_CONFIG_HOME` set to `$HOME/.config` and my `windowchefrc` is in `$HOME/.config/windowchef/`. I have tried the git version here and both from aur.

I also did `chmod +x` on `windowchefrc` so that shouldn't be an issue either. (file isn't owned by root)

EDIT: I have also build the debug version and get the same error in the log file it outputs.

OS: Arch Linux
Kernel: 4.19.2
Shell: bash
windowchef: v0.4.1-22-gfc61af7
waitron: v0.4.1-22-gfc61af7

**Comment by tudurom** [comment]
Sorry for being late. I pushed a commit that prints better error messages. You can try again now.
