### ISSUE TITLE
NetBSD xcb-randr not available

### ISSUE THREAD

**Issue by margaretjoanmiller** [tudurom/windowchef#65]
Hi! There's unfortunately no package for xcb-randr in NetBSD, however it looks like xcb-randr is already installed because libxcbrandr exists. Any advice?

**Comment by margaretjoanmiller** [comment]
I tried using pkgconf as you suggested in a similar issue on OpenBSD to no avail.

**Comment by tudurom** [comment]
Do you have `/lib/pkgconfig/xcb-rander.pc` on your system?
