### ISSUE TITLE
workspace fanatics incoming

### ISSUE THREAD

**Issue by mintyleaf** [tudurom/windowchef#67]
hey there
i just want to know is it normal behaviour that if i cycling through "workspaces" some windows (100% telegram desktop, sometimes i've catched this on st terminals) rests mapped on workspace, until i set current group again.
to avoid this i just maked a script like this:
```
  #!/bin/sh
  
  waitron group_activate_specific $1
  waitron group_activate_specific $1
  
  st -g 0x0 & sleep 0.1 && kill $!
```

also here i'm calling st and killing him for update _NET_CURRENT_WORKSPACE, so my little utility that instantly grabs this prop can show me through the lemonbar what desktop is setted right now

**Comment by tudurom** [comment]
to be honest, i have no idea. will investigate

**Comment by tudurom** [comment]
Closing in favour of #68.
