### ISSUE TITLE
Gaps between windows in virtual grid

### ISSUE THREAD

**Issue by dialuplama** [tudurom/windowchef#7]
Hello,

Is there way to set gaps between windows when put them in virtual grid?

Also i have notice that windows in virtual grid don't respect gaps around monitor.

**Comment by tudurom** [comment]
Working on it!

**Comment by tudurom** [comment]
Done in b057e42a2f13820a6d869f2a38fd34f32ec22a59.

**Comment by tudurom** [comment]
WEW WRONG COMMIT

**Comment by tudurom** [comment]
sorry for that, hold on let me push it

**Comment by tudurom** [comment]
ok fixed in 5e6b37740d2df05d3b2ea63099f51a7fcee4a98f

**Comment by dialuplama** [comment]
Thank you. All works great. But i have noticed that there is difference in size of monitor padding when using virtual grid and window snap. The difference exactly in border width. Then i increased border width and monitor padding has disappeared. Sorry for my bad english. Maybe screenshots will explain better. 

Window snap:
![2016-10-03-195810_1920x1200_scrot](https://cloud.githubusercontent.com/assets/16153634/19046385/c1449408-89a5-11e6-8605-20b1a94ee6b6.png)

Virtual grid:
![2016-10-03-195826_1920x1200_scrot](https://cloud.githubusercontent.com/assets/16153634/19046390/cb6a8ac8-89a5-11e6-961b-afeb48b445ec.png)

**Comment by tudurom** [comment]
Confirmed. Working on a fix! Thank you!

Note for future self: check your math.

**Comment by tudurom** [comment]
Fixed in a44189ab8c0b250b54ff11bbb4184997a6969af4
