### ISSUE TITLE
enable_last_window_focusing true and group_toggle

### ISSUE THREAD

**Issue by neyuki** [tudurom/windowchef#70]
Hello, if i have enable_last_window_focusing on and have a window in group X
then that window opens a dialog window in same group X. After that (2 windows in group X with focused second one) I do group_toggle. Only second one window that was focused is removed. Main one still there.

Is that a normal behavior?

**Comment by tudurom** [comment]
Which one disappeared, the main window or the dialog?

**Comment by neyuki** [comment]
second one, the dialog, that was focused. main one is still there. but it is a group toggle, why them both doesn't get lost?

**Comment by tudurom** [comment]
Windowchef does not add dialog windows to the group of the parent automatically. I think that can be accomplished by respecting the ICCCM `WM_TRANSIENT_FOR` property. However, there is currently no such functionality.

**Comment by neyuki** [comment]
yes it doesn't. but you can do it. with ruler or just manual, after dialog win is appear.

**Comment by tudurom** [comment]
i am going to close the issue, it is normal behaviour.

If you want to submit a PR to automatically add dialogs to the group based on `WM_TRANSIENT_FOR`, I will accept it.

**Comment by neyuki** [comment]
How it's work right now:

if enable_last_window_focusing is 0, any windows in group despite their type is removed by group toggle.
if enable_last_window_focusing is 1, after dialog window appear and focused group toggle will remove only it, but main window will still be there.

Can u explain me a logic, isn't a group is superior in hierarchy? If i have some windows _in_ group irrelevant their type, relationship with each other, anything else, group toggle must shut all of them.

I have a "ruler" what says what kind of windows belong to group. I have a group toggle.

**Comment by tudurom** [comment]
Can you try the `issue_68` branch?

**Comment by tudurom** [comment]
> if enable_last_window_focusing is 0, any windows in group despite their type is removed by group toggle.
> if enable_last_window_focusing is 1, after dialog window appear and focused group toggle will remove only it, but main window will still be there (tested on firefox and it "save as" dialog).
> 
> Can u explain me a logic, isn't a group is superior in hierarchy? If i have some windows _in_ group irrelevant their type, relationship with each other, anything else, group toggle must shut all of them.

I think I get it, are you reporting the exact problem as #68?

**Comment by neyuki** [comment]
just checked issue_68 branch, no, it doesn't solve that question for me.

still, if enable_last_window_focusing is true, dialog window dissapear but main one is still there for group toggle.

may be it is because: group toggle remove all group windows, but last window is focused again and show up?
