### ISSUE TITLE
Rounded corners support with picom

### ISSUE THREAD

**Issue by humky** [tudurom/windowchef#74]
When using picom with rounded corners support https://github.com/ibhagwan/picom Windowchef doesn't render borders properly. Using external tools to set borders produce same ugly corners
![corners-bug](https://user-images.githubusercontent.com/84576031/146399650-ddca63d4-f436-461f-b223-b6459e66f192.png)
(ignore bottom window shadow bug, that's common issue among all WMs)

**Comment by tudurom** [comment]
Hmm makes sense, as the border is a rectangle that is cropped by the rounding algorithm of Picom.

Can you tell me some similar WMs that support this?

**Comment by humky** [comment]
I just tested some WMs, turns out it's not as common as I thought, bspwm supports it, I was using it for 2 or 3 years, so I was oblivious about others.

**Comment by acoolstraw** [comment]
JWM also supports it pretty well, would be a great feature for aesthetics purposes, just a slight curve makes a lot of difference
