### ISSUE TITLE
Crashes when using 0 as workspace name

### ISSUE THREAD

**Issue by greduan** [tudurom/windowchef#8]
I tried to use `0` as my group name and that crashed it. I seem to also remember somebody mentioned that if you don't use the default `1-4` it crashes but I can't confirm that.

Reproduce steps:
- sxhkd config:
  
  ```
  super + {_,shift +}{1-9,0}
    waitron {group_toggle,group_add_window} {1-9,0}
  ```
- Assign couple windows to group `0`
- Toggle group `0`
- Profit?

**Comment by tudurom** [comment]
Group numbers start from 1. Also, the crashy situation is fixed. Don't forget to set the number of groups accordingly in the config file.
