### ISSUE TITLE
Cycle only windows that belong to group window is in

### ISSUE THREAD

**Issue by greduan** [tudurom/windowchef#9]
Unless of course the window has no group in which case cycle all windows.

I find it very tedious when I switch to a new group and I want to switch to the other window but I gotta go through a bunch of other windows to it.

This is what I came up with to alleviate this.

**Comment by tudurom** [comment]
Great idea! I will implement it this afternoon (EEST).

**Comment by tudurom** [comment]
i say that if the window doesn't belong to any group it should just cycle between windows without group. Ok?

**Comment by tudurom** [comment]
done in 5e6b37740d2df05d3b2ea63099f51a7fcee4a98f

**Comment by greduan** [comment]
Nice!

**Comment by tudurom** [comment]
just realized I made a typo. So:
- if the window belongs to a group, cycle through all windows that belong to that group
- if the window doesn't belong to any group, cycle through all windows that don't belong to a group.

**Comment by greduan** [comment]
Indeed, that is what I was thinking.

**Comment by tudurom** [comment]
Windows without a group actually belong to the `NULL_GROUP` group. So in reality it's the same thing.
